# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Demo

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.10.0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: 'pnpm'
      
    - name: Install and build root project
      run: |
          pnpm install
          pnpm build
          
    - name: Install and build demo project
      working-directory: ./demo
      run: |
          pnpm install
          pnpm build
          
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./demo/dist/
        
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        token: ${{ github.token }}
          
          
